repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 24.8.0 # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Use the latest version
    hooks:
      - id: flake8
